export const INITIAL_STATE = "INITIAL_STATE";
export const SEARCH_PRODUCT_STATE = "SEARCH_PRODUCT_STATE";
export const INPUT_EMAIL_STATE = "INPUT_EMAIL_STATE";
export const INPUT_NAME_STATE = "INPUT_NAME_STATE";
export const INPUT_ADDRESS_STATE = "INPUT_ADDRESS_STATE";
export const SUBSCRIBE_STATE = "SUBSCRIBE_STATE";
export const CONFIRM_SUBSCRIBE_STATE = "CONFIRM_SUBSCRIBE_STATE";
export const SUBSCRIPTION_STATE = "SUBSCRIPTION_STATE";